spring:
#   port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
        hibernate:
          "[format_sql]": true
    # show-sql: true
    # generate-ddl: true